maps:
  - world
  - spawn
  - lobby
  - map_2castles
  - map_2fort
  - map_bootcamp
  - map_caverns
  - map_clay
  - map_clay_nb
  - map_cliffs
  - map_dev
  - map_frostnova
  - map_forest
  - map_ice
  - map_ice_nb
  - map_ice_ad
  - map_monolith
  - map_mountain
  - map_overgrown
  - map_ravine
  - map_river
  - map_serenity
  - map_ships
  - map_skylands
  - map_underworld
  - map_urban
  - map_valley
  - map_valley_nb
  - map_void
  - map_wall
  - map_biohazard
  - map_oasis
  - map_leafy_canyon
  - map_spawn_ruins
  - map_colliery
  - map_candyland
  - map_hotel_monsenor
  - map_coast_classic
  - map_coast_koth
  - map_void_koth
  - map_lazarus
  - map_ashlands
  - map_slime_world